---

- name: Ensures that the necessary gems are installed
  hosts: "{{ node }}"
  user: "{{ user }}"
  sudo: no

  tasks:

    - include: app_vars.yml

    - name: Bundle install
      command: bash -lc "bundle install" chdir={{ app_path }}/
      register: command_result
      failed_when: "command_result.rc != 0"
      changed_when: "command_result.rc == 2"
