---

- name: Ensures Bundler installation
  hosts: "{{ node }}"
  user: "{{ user }}"
  sudo: no

  tasks:

  - name: Install Bundler
    command: bash -lc "gem install bundler"
    register: command_result
    failed_when: "command_result.rc != 0"
    changed_when: "'bundler-1.9.1' not in command_result.stdout"
