---

- name: Ensures that Java 8 is available
  hosts: "{{ node }}"
# connection: local
  user: ansible2
  sudo: yes

  tasks:

  - name: Ensures python software properties present
    apt: name=python-software-properties state=present

  - name: Ensures ppa:webupd8team/java is present
    apt_repository: repo='ppa:webupd8team/java' state=present

  - name: Updates the index
    apt: update_cache=yes

  - name: Agrees with license before it shows up
    shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

  - name: Ensures java 8 package is installed
    apt: pkg=oracle-java8-installer update_cache=yes state=present
